### ISSUE TITLE
Configuration Docs

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/OpenPype#1453]
Global holder for settings sections that need to be documented

- [ ] Project settings > Deadline > Publish > MayaSubmitDeadline
- [ ] Project settings > Deadline > Publish > NukeSubmitDeadline
- [x] Project settings > Deadline > Publish > HarmonySubmitDeadline
- [x] Project settings > Deadline > Publish > AfterEffectsSubmitDeadline
- [ ] Project settings > Ftrack > Events > sync_to_avalon
- [ ] Project settings > Ftrack > Events > prepare_project
- [ ] Project settings > Ftrack > Events > sync_hier_entity_attributes
- [ ] Project settings > Ftrack > Events > clone_review_session
- [ ] Project settings > Ftrack > Events > thumbnail_updates
- [ ] Project settings > Ftrack > Events > user_assignment
- [ ] Project settings > Ftrack > Events > status_update
- [ ] Project settings > Ftrack > Events > status_task_to_parent
- [ ] Project settings > Ftrack > Events > status_task_to_version
- [ ] Project settings > Ftrack > Events > status_version_to_task
- [ ] Project settings > Ftrack > Events > first_version_status
- [ ] Project settings > Ftrack > Events > next_task_update
- [ ] Project settings > Ftrack > User_handlers > application_launch_statuses
- [ ] Project settings > Ftrack > User_handlers > create_update_attributes
- [ ] Project settings > Ftrack > User_handlers > prepare_project
- [ ] Project settings > Ftrack > User_handlers > clean_hierarchical_attr
- [ ] Project settings > Ftrack > User_handlers > delete_asset_subset
- [ ] Project settings > Ftrack > User_handlers > delete_old_versions
- [ ] Project settings > Ftrack > User_handlers > delivery_action
- [ ] Project settings > Ftrack > User_handlers > store_thubmnail_to_avalon
- [ ] Project settings > Ftrack > User_handlers > job_killer
- [ ] Project settings > Ftrack > User_handlers > sync_to_avalon_local
- [ ] Project settings > Ftrack > User_handlers > get_tasks_event_to_csv
- [ ] Project settings > Ftrack > User_handlers > seed_project
- [ ] Project settings > Ftrack > Publish > IntegrateFtrackNote
- [ ] Project settings > Ftrack > Publish > ValidateFtrackAttributes
- [ ] Project settings > Global > Publish > IntegrateHeroVersion
- [ ] Project settings > Global > Publish > ExtractJpegEXR
- [x] Project settings > Global > Publish > ExtractReview
- [ ] Project settings > Global > Publish > ExtractBurnin
- [x] Project settings > Global > Publish > IntegrateAssetNew
- [ ] Project settings > Global > Publish > ProcessSubmittedJobOnFarm
- [ ] Project settings > Global > Tools > creator
- [ ] Project settings > Global > Tools > Workfiles
- [ ] Project settings > Global > Project_folder_structure > __project_root__
- [x] Project settings > Global > Sync_server > enabled
- [x] Project settings > Global > Sync_server > config
- [x] Project settings > Global > Sync_server > sites
- [ ] Project settings > Global > Project_plugins
- [ ] Project anatomy > Imageio > Hiero > workfile
- [ ] Project anatomy > Imageio > Hiero > regexInputs
- [ ] Project anatomy > Imageio > Nuke > viewer
- [ ] Project anatomy > Imageio > Nuke > workfile
- [ ] Project anatomy > Imageio > Nuke > nodes
- [ ] Project anatomy > Imageio > Nuke > regexInputs

[cuID:[OP-1158](https://app.clickup.com/t/yjxzky)]

**Comment by jezscha** [comment]
@mkolar I was about to work on ImageIO settins but I am not sure were exaclty Nuke/Hiero settings should be documented.. https://openpype.io/docs/admin_settings_project_anatomy#colour-management-and-formats Here it is prepared, but as it is Nuke / Hiero related, shouldn't this be also part of it?

**Comment by mkolar** [comment]
closing this as stale
