### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#2490]
This is attempt to reboot reboot of API documentation. We really need to do it. Solution to it is maybe switch from [Sphinx](https://www.sphinx-doc.org/en/master/) to [pdoc3](https://pdoc3.github.io/pdoc/) as it might be easier to tackle then sphinx beast.

Goal is to be able to auto (re)generate API documentation on demand and display it in human compatible way even if it is not complete.

Borrowing citation from pdoc3 site:

> Documentation is like sex: when it is good, it is very, very good;
and when it is bad, it is better than nothing.

Steps to achieve it:

- [x] Decide between Sphinx or pdoc3
- [ ] Configure it so it will ingest most of the relevant code (and ignore vendored, ...)
- [ ] Tweak templates if necessary
- [ ] Set CI to build it and link it with openpype.io web
- [ ] Gradually improve docstring 

[cuID:[OP-2318](https://app.clickup.com/t/1zfq9h4)]

**Comment by antirotor** [comment]
Previous attempts: #834 #210

**Comment by antirotor** [comment]
Looks like Sphinx is still the way to go, pdoc3 isn't sophisticated enough to handle import hell we are dealing with.

**Comment by BigRoy** [comment]
Just wanted to bump this issue since it came up on Discord in `#documentation` channel recently. Would be great to get this ball rolling again in a way.

**Comment by mkolar** [comment]
We're now adding sphinx docs to ynput/ayon-core and will be for addons too. Closing this issue as it will have to be sorted on multiple fronts.
